spring:
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    username: ldp_local
    password: ldplocalpwd
    url: 'jdbc:mysql://localhost:3306/ldp_local'
  jpa:
    show-sql: true



